language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gnuplot

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - mdbook build docs
  - mdbook test docs
  - cp -r target/criterion docs/book/benchmarks

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/book
  keep-history: false
  verbose: true
  on:
    branch: master
    rust: stable
