[package]
authors = ["Krishan Wyse <kwysek@gmail.com>"]
build = "build.rs"
name = "euler-solutions"
version = "0.1.0"

[dependencies]
num = "0.1.42"

[dependencies.kb]
git = "https://github.com/kwyse/kb"
