[package]
name = "euler-solutions"
authors = ["Krishan Wyse <kwysek@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
paste = "0.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
