[package]
name = "euler-solutions"
authors = ["Krishan Wyse <kwysek@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false
