baseURL = "https://www.kwyse.com/euler-solutions"
title = "Project Euler Solutions"
theme = "hugo-notepadium"
copyright = "© 2020 Krishan Wyse"
relativeURLs = true

[markup.highlight]
codeFences = true
noClasses = false

[params]
style = "light"

[params.math]
enable = true 

[params.syntax]
theme = "xcode"
