//! Problem 2: Even Fibonacci numbers
//!
//! Each new term in the Fibonacci sequence is generated by adding the previous
//! two terms. By starting with 1 and 2, the first 10 terms will be:
//!
//! 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//!
//! By considering the terms in the Fibonacci sequence whose values do not
//! exceed four million, find the sum of the even-valued terms.

/// Sums even-valued Fibonacci numbers up to a limit
pub fn sum_of_even_value_fibs(limit: u32) -> u32 {
    EvenFibIter::default().take_while(|&n| n < limit).sum()
}

/// Yields even-valued Fibonacci numbers
pub struct EvenFibIter { a: u32, b: u32 }

impl Default for EvenFibIter {
    fn default() -> Self {
        Self { a: 0, b: 2 }
    }
}

impl Iterator for EvenFibIter {
    type Item = u32;

    fn next(&mut self) -> Option<Self::Item> {
        let curr = self.a;
        self.a = self.b;
        self.b = 4 * self.a + curr;

        Some(curr)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sum_of_even_value_fibonacci_numbers_is_calculated() {
        assert_eq!(sum_of_even_value_fibs(10), 10);
    }

    #[test]
    fn even_fibonacci_numbers_are_generated() {
        let mut fibs = EvenFibIter::default();

        assert_eq!(fibs.next(), Some(0));
        assert_eq!(fibs.next(), Some(2));
        assert_eq!(fibs.next(), Some(8));
        assert_eq!(fibs.next(), Some(34));
        assert_eq!(fibs.next(), Some(144));
    }

    #[test]
    fn p002() {
        assert_eq!(sum_of_even_value_fibs(4_000_000), 4_613_732);
    }
}
