name: ci

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup emacs
        uses: purcell/setup-emacs@master
        with:
          version: 26.3

      - name: Tangle files
        run: emacs ./euler.org --batch --eval='(org-babel-tangle)' --kill

      - name: Build solutions
        run: cargo build --verbose

      - name: Test solutions
        run: cargo test --verbose

      - name: Clone Org-mode exporter
        run: git clone https://github.com/kaushalmodi/ox-hugo.git ox-hugo

      - name: Export Org file to Markdown
        run: emacs ./euler.org --batch -L ./ox-hugo -l ox-hugo.el --eval='(org-hugo-export-wim-to-md t)' --kill

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --minify --theme=hugo-notepadium

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
